server.port: 8081

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/academia
  username: postgres
  password: 12345678
  
 jpa:
  show-sql: true  
  hibernate:
   ddl-auto: update
   hibernate.format_sql: true
   
logging:
 level:
  org:
   hibernate:
    type: trace
    